module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.19

replace github.com/efficientgo/core => github.com/efficientgo/core v1.0.0-rc.0.0.20220828074345-1974bfa191ce

replace github.com/oklog/run-v100 => github.com/oklog/run v1.0.0

require github.com/bwplotka/bingo-testmodule v0.0.0-20221007091003-fe4d42a37d92 // buildable
