module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require (
	github.com/pkg/errors v0.9.1 // indirect
	github.com/prometheus/common v0.10.0 // indirect
	github.com/prometheus/promu v0.2.0
	github.com/spf13/cobra v1.0.0 // indirect
	github.com/spf13/viper v1.7.0 // indirect
)
