module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require (
	golang.org/x/mod v0.3.0 // indirect
	golang.org/x/tools v0.0.0-20200519204825-e64124511800 // cmd/goimports
)
