module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

replace github.com/Kunde21/markdownfmt/v2 => github.com/bwplotka/markdownfmt/v2 v2.0.0-20201225192631-f2e7830d9793

require github.com/bwplotka/mdox v0.2.0
