module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

// Current version of golang.org/x/sys in github.com/gomods/athens does not
// compile on darwin/arm64
replace golang.org/x/sys => golang.org/x/sys v0.0.0-20220330033206-e17cdc41300f

require github.com/gomods/athens v0.10.0 // cmd/proxy
