// Copyright (c) Bartłomiej Płotka @bwplotka
// Licensed under the Apache License 2.0.

package gobin

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/bwplotka/gobin/pkg/testutil"
)

func TestCreateGoFileWithPackages(t *testing.T) {
	tmpDir, err := ioutil.TempDir(os.TempDir(), "gobin")
	testutil.Ok(t, err)
	defer testutil.Ok(t, os.RemoveAll(tmpDir))

	t.Run("ok", func(t *testing.T) {
		b := &strings.Builder{}
		testutil.Ok(t, CreateGoFileWithPackages(filepath.Join(tmpDir, "somefile.go"),
			"github.com/bwplotka/gobin2/yolo",
			"github.com/bwplotka/gobin3",
			"github.com/bwplotka/gobin2/and/yolo",
			"github.com/bwplotka/gobin/a",
			"github.com/bwplotka/gobin",
			"golang.org/x/tools/cmd/goimports",
			"github.com/bwplotka/gobin/a/b",
		))
		testutil.Equals(t, `// Temporary code generated by https://github.com/bwplotka/gobin. DO NOT EDIT.
// +build tools
package tmp

import (
	_ "github.com/bwplotka/gobin"
	_ "github.com/bwplotka/gobin/a"
	_ "github.com/bwplotka/gobin/a/b"
	_ "github.com/bwplotka/gobin2/and/yolo"
	_ "github.com/bwplotka/gobin2/yolo"
	_ "github.com/bwplotka/gobin3"
	_ "golang.org/x/tools/cmd/goimports"
)
`, b.String(), "does not match, got %v", b.String())
	})
}
