module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.17

replace github.com/bwplotka/bingo => github.com/pkg/errors v0.9.1

require github.com/bwplotka/bingo/testdata/module_with_replace v0.0.0-20210109165512-ccbd4039b94a // buildable
