

faillint-exists: $(FAILLINT)
	@echo "checking faillint"
	@test $(FAILLINT) || error "no file"

goimports-exists: $(GOIMPORTS)
	@echo "checking goimports"
	@test $(GOIMPORTS) || error "no file"

goimports2-exists: $(GOIMPORTS2)
	@echo "checking goimports2"
	@test $(GOIMPORTS2) || error "no file"
