// Code generated by https://github.com/bwplotka/gobin . DO NOT EDIT.
// NOTE: Actually you can edit just fine, just don't be surprised if the file will be rewritten at some point by
// gobin tool.
//
// This file is and extended version of somethings that is called "tools.go package" described here: https://github.com/golang/go/issues/25922#issuecomment-590529870
// It allows go modules to maintain certain version of binaries you or your project use.
// Main extension that bwplotka/gobin adds, is that the file has to be stored as the separate go module file, which allows
// separation of dev tools from critical, production code which is th key.
//
// Read more on https://github.com/bwplotka/gobin .

// +build tools
package _gobin

import (
	_ "golang.org/x/tools/cmd/goimports"
)

const (
	// FileVersion represents version of this file. This will tell future versions of gobin how to parse this file.
	FileVersion = "v1.0.0"
	// Gobin version used to generate this file. Used for debugging only.
	GobinVersion = "??"
)
