module gobin // Auto generated by https://github.com/bwplotka/gobin. DO NOT EDIT

go 1.14

require (
	github.com/bwplotka/gobin v0.1.0-rc.2
	github.com/oklog/run v1.1.0
	github.com/pkg/errors v0.9.1
	golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543 // indirect
)
