module _ // Auto generated by https://github.com/bwplotka/gobin. DO NOT EDIT

go 1.14

require (
	github.com/bwplotka/gobin v0.1.0-rc.2
	golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543 // indirect
)
